# Dockerfile for Ubuntu-based Kafka

FROM quay.io/signalfuse/maestro-base:ubuntu-16.10-jdk8
MAINTAINER Janet Yu <jwy@signalfx.com>

ENV DEBIAN_FRONTEND noninteractive

ADD ./install_kafka /opt/install_kafka
RUN /opt/install_kafka

ADD run.py /opt/kafka/.docker/

WORKDIR /opt/kafka
CMD ["python", "/opt/kafka/.docker/run.py"]
